"""
LangGraph Code Generator

This module generates executable LangGraph Python code from AWDL IR.
"""

from typing import List, Optional
from textwrap import dedent, indent

from awdl.ir.workflow import Workflow, WorkflowElement
from awdl.ir.elements import Agent, Tool
from awdl.ir.conditions import Condition, WhileLoop, ForLoop
from awdl.compiler.base import BaseCompiler
from awdl.compiler.langgraph.graph_builder import GraphBuilder, Edge, ConditionalEdge
from awdl.compiler.langgraph.state import StateGenerator


class LangGraphCompiler(BaseCompiler):
    """
    Compiles AWDL IR to LangGraph executable Python code.
    
    This compiler transforms the framework-agnostic IR into LangGraph's
    graph-based execution model. The key transformation is converting
    variable dependencies into explicit graph edges.
    """
    
    def __init__(self, workflow: Workflow):
        """
        Initialize the LangGraph compiler.
        
        Args:
            workflow: The workflow to compile
        """
        super().__init__(workflow)
        self.graph_builder = GraphBuilder(workflow)
        self.state_generator = StateGenerator(workflow)
    
    def get_target_name(self) -> str:
        """Return the target framework name."""
        return "langgraph"
    
    def compile(self) -> str:
        """
        Compile the workflow to LangGraph Python code.
        
        Returns:
            Generated Python code as a string
        """
        code_parts = []
        
        # Header comment
        code_parts.append(self._generate_header())
        
        # Imports
        code_parts.append(self._generate_imports())
        
        # State class
        code_parts.append(self._generate_state_class())
        
        # Node functions (agents and tools)
        code_parts.append(self._generate_node_functions())
        
        # Condition functions
        condition_funcs = self._generate_condition_functions()
        if condition_funcs:
            code_parts.append(condition_funcs)
        
        # Graph construction
        code_parts.append(self._generate_graph())
        
        # Entry point
        code_parts.append(self._generate_entry_point())
        
        return "\n\n".join(filter(None, code_parts))
    
    def _generate_header(self) -> str:
        """Generate the file header comment."""
        return dedent(f'''\
            """
            Auto-generated LangGraph workflow from AWDL.
            
            Workflow: {self.workflow.name}
            Version: {self.workflow.version}
            
            Generated by AWDL Compiler (target: langgraph)
            """
        ''').strip()
    
    def _generate_imports(self) -> str:
        """Generate import statements."""
        imports = [
            "from typing import TypedDict, Any, Optional",
            "from langgraph.graph import StateGraph, END",
        ]
        
        # Add stdlib imports based on what's used
        agent_types = set()
        tool_types = set()
        
        for element in self.workflow.get_all_elements_flat():
            if isinstance(element, Agent):
                agent_types.add(element.agent_type)
            elif isinstance(element, Tool):
                tool_types.add(element.tool_type)
        
        # Add imports for agents
        if agent_types:
            imports.append("")
            imports.append("# Agent imports")
            for agent_type in sorted(agent_types):
                imports.append(f"# from stdlib.agents import {agent_type}")
        
        # Add imports for tools
        if tool_types:
            imports.append("")
            imports.append("# Tool imports")
            for tool_type in sorted(tool_types):
                imports.append(f"# from stdlib.tools import {tool_type}")
        
        return "\n".join(imports)
    
    def _generate_state_class(self) -> str:
        """Generate the state TypedDict class."""
        return self.state_generator.generate_state_class("WorkflowState")
    
    def _generate_node_functions(self) -> str:
        """Generate node functions for all agents and tools."""
        functions = []
        
        for element in self.workflow.get_all_elements_flat():
            if isinstance(element, Agent):
                functions.append(self._generate_agent_function(element))
            elif isinstance(element, Tool):
                functions.append(self._generate_tool_function(element))
        
        return "\n\n".join(functions)
    
    def _generate_agent_function(self, agent: Agent) -> str:
        """Generate a node function for an agent."""
        func_name = f"{agent.element_id}_node"
        
        # Build input extraction
        input_lines = []
        for port_name, var_name in agent.inputs.items():
            input_lines.append(f'    {port_name} = state["{var_name}"]')
        
        # Build output assignment
        output_lines = []
        for port_name, var_name in agent.outputs.items():
            output_lines.append(f'        "{var_name}": result.get("{port_name}", ""),')
        
        inputs_code = "\n".join(input_lines) if input_lines else "    pass  # No inputs"
        outputs_code = "\n".join(output_lines) if output_lines else '        # No outputs'
        
        # Build the function
        code = dedent(f'''\
            def {func_name}(state: WorkflowState) -> dict:
                """
                Agent node: {agent.agent_type}
                ID: {agent.element_id}
                """
                # Extract inputs from state
            {inputs_code}
                
                # TODO: Implement actual agent call
                # For now, return a placeholder
                result = {{
                    "response": f"[{agent.agent_type}] Processed input",
                }}
                
                # Return outputs to update state
                return {{
            {outputs_code}
                }}
        ''')
        
        return code.strip()
    
    def _generate_tool_function(self, tool: Tool) -> str:
        """Generate a node function for a tool."""
        func_name = f"{tool.element_id}_node"
        
        # Build input extraction
        input_lines = []
        for port_name, var_name in tool.inputs.items():
            input_lines.append(f'    {port_name} = state["{var_name}"]')
        
        # Build output assignment
        output_lines = []
        for port_name, var_name in tool.outputs.items():
            output_lines.append(f'        "{var_name}": result.get("{port_name}", ""),')
        
        inputs_code = "\n".join(input_lines) if input_lines else "    pass  # No inputs"
        outputs_code = "\n".join(output_lines) if output_lines else '        # No outputs'
        
        # Build the function
        code = dedent(f'''\
            def {func_name}(state: WorkflowState) -> dict:
                """
                Tool node: {tool.tool_type}
                ID: {tool.element_id}
                """
                # Extract inputs from state
            {inputs_code}
                
                # TODO: Implement actual tool call
                # For now, return a placeholder
                result = {{
                    "results": f"[{tool.tool_type}] Executed",
                }}
                
                # Return outputs to update state
                return {{
            {outputs_code}
                }}
        ''')
        
        return code.strip()
    
    def _generate_condition_functions(self) -> Optional[str]:
        """Generate condition functions for conditional edges."""
        functions = []
        
        for element in self.workflow.elements:
            if isinstance(element, Condition):
                functions.append(self._generate_condition_function(element))
        
        if not functions:
            return None
        
        return "\n\n".join(functions)
    
    def _generate_condition_function(self, condition: Condition) -> str:
        """Generate a condition function for routing."""
        func_name = f"should_{condition.element_id}"
        condition_code = condition.expression.to_python()
        
        code = dedent(f'''\
            def {func_name}(state: WorkflowState) -> str:
                """
                Condition function for: {condition.element_id}
                Expression: {condition.expression}
                """
                if {condition_code}:
                    return "then"
                return "else"
        ''')
        
        return code.strip()
    
    def _generate_graph(self) -> str:
        """Generate the graph construction code."""
        lines = [
            "# Build the workflow graph",
            "workflow = StateGraph(WorkflowState)",
            "",
            "# Add nodes",
        ]
        
        # Add nodes
        for element in self.workflow.get_all_elements_flat():
            if isinstance(element, (Agent, Tool)):
                node_name = element.element_id
                func_name = f"{element.element_id}_node"
                lines.append(f'workflow.add_node("{node_name}", {func_name})')
        
        lines.append("")
        lines.append("# Add edges (derived from variable dependencies)")
        
        # Get edges from graph builder
        edges = self.graph_builder.build_edges()
        conditional_edges = self.graph_builder.build_conditional_edges()
        
        # Add regular edges
        for edge in edges:
            lines.append(f'workflow.add_edge("{edge.source}", "{edge.target}")')
        
        # Add conditional edges
        if conditional_edges:
            lines.append("")
            lines.append("# Add conditional edges")
            for cond_edge in conditional_edges:
                routes_str = ", ".join(
                    f'"{k}": "{v}"' if v != "__end__" else f'"{k}": END'
                    for k, v in cond_edge.routes.items()
                )
                lines.append(
                    f'workflow.add_conditional_edges("{cond_edge.source}", '
                    f'{cond_edge.condition_func}, {{{routes_str}}})'
                )
        
        # Set entry point
        entry_point = self.graph_builder.get_entry_point()
        if entry_point:
            lines.append("")
            lines.append(f'workflow.set_entry_point("{entry_point}")')
        
        return "\n".join(lines)
    
    def _generate_entry_point(self) -> str:
        """Generate the entry point for running the workflow."""
        initial_state = self.state_generator.get_initial_state()
        
        code = dedent(f'''\
            # Compile the graph
            app = workflow.compile()
            
            
            # Initial state
            {initial_state}
            
            
            if __name__ == "__main__":
                # Run the workflow
                result = app.invoke(initial_state)
                print("Final state:", result)
        ''')
        
        return code.strip()

